/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { INativeTokenWallet, INativeTokenWalletInterface } from "../../interfaces/INativeTokenWallet.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "deposit",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class INativeTokenWallet__factory {
    static readonly abi = _abi;
    static createInterface(): INativeTokenWalletInterface {
      return new Interface(_abi) as INativeTokenWalletInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): INativeTokenWallet {
      return new Contract(address, _abi, runner) as unknown as INativeTokenWallet;
    }
  }
  