/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace IGatewayStructs {
      
    export type ReceiverWithdrawStruct = {receiver: string, amount: BigNumberish, tokenId: BigNumberish}

    export type ReceiverWithdrawStructOutput = [receiver: string, amount: bigint, tokenId: bigint] & {receiver: string, amount: bigint, tokenId: bigint }
  
    }

  export interface GatewayInterface extends Interface {
    getFunction(nameOrSignature: "UPGRADE_INTERFACE_VERSION" | "currencyTokenId" | "deposit" | "getTokenAddress" | "initialize" | "minBridgingAmount" | "minFee" | "minOperationFee" | "minTokenBridgingAmount" | "nativeTokenPredicate" | "owner" | "proxiableUUID" | "registerToken" | "renounceOwnership" | "setDependencies" | "setMinAmounts" | "tokenFactory" | "transferOwnership" | "updateValidatorsChainData" | "upgradeToAndCall" | "validators" | "version" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposit" | "DepositedToken" | "FundsDeposited" | "Initialized" | "MinAmountsUpdated" | "OwnershipTransferred" | "TTLExpired" | "TokenRegistered" | "Upgraded" | "ValidatorSetUpdatedGW" | "ValidatorsSetUpdated" | "Withdraw" | "WithdrawToken"): EventFragment;

    encodeFunctionData(functionFragment: 'UPGRADE_INTERFACE_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'currencyTokenId', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values: [BytesLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'getTokenAddress', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'initialize', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'minBridgingAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'minFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'minOperationFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'minTokenBridgingAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'nativeTokenPredicate', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerToken', values: [AddressLike, BigNumberish, string, string]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setDependencies', values: [AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setMinAmounts', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'tokenFactory', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateValidatorsChainData', values: [BytesLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'validators', values?: undefined): string;
encodeFunctionData(functionFragment: 'version', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish, IGatewayStructs.ReceiverWithdrawStruct[], BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'UPGRADE_INTERFACE_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currencyTokenId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minBridgingAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minOperationFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minTokenBridgingAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nativeTokenPredicate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDependencies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinAmounts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateValidatorsChainData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validators', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'version', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace DepositEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositedTokenEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsDepositedEvent {
      export type InputTuple = [sender: AddressLike, value: BigNumberish];
      export type OutputTuple = [sender: string, value: bigint];
      export interface OutputObject {sender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinAmountsUpdatedEvent {
      export type InputTuple = [minFee: BigNumberish, minAmount: BigNumberish, minTokenAmount: BigNumberish, minOperationFee: BigNumberish];
      export type OutputTuple = [minFee: bigint, minAmount: bigint, minTokenAmount: bigint, minOperationFee: bigint];
      export interface OutputObject {minFee: bigint, minAmount: bigint, minTokenAmount: bigint, minOperationFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TTLExpiredEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenRegisteredEvent {
      export type InputTuple = [name: string, symbol: string, tokenId: BigNumberish, contractAddress: AddressLike, isLockUnlockToken: boolean];
      export type OutputTuple = [name: string, symbol: string, tokenId: bigint, contractAddress: string, isLockUnlockToken: boolean];
      export interface OutputObject {name: string, symbol: string, tokenId: bigint, contractAddress: string, isLockUnlockToken: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidatorSetUpdatedGWEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidatorsSetUpdatedEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [destinationChainId: BigNumberish, sender: AddressLike, receivers: IGatewayStructs.ReceiverWithdrawStruct[], fee: BigNumberish, operationFee: BigNumberish, value: BigNumberish];
      export type OutputTuple = [destinationChainId: bigint, sender: string, receivers: IGatewayStructs.ReceiverWithdrawStructOutput[], fee: bigint, operationFee: bigint, value: bigint];
      export interface OutputObject {destinationChainId: bigint, sender: string, receivers: IGatewayStructs.ReceiverWithdrawStructOutput[], fee: bigint, operationFee: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawTokenEvent {
      export type InputTuple = [sender: AddressLike, receiver: string, amount: BigNumberish];
      export type OutputTuple = [sender: string, receiver: string, amount: bigint];
      export interface OutputObject {sender: string, receiver: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Gateway extends BaseContract {
    
    connect(runner?: ContractRunner | null): Gateway;
    waitForDeployment(): Promise<this>;

    interface: GatewayInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    UPGRADE_INTERFACE_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    currencyTokenId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [_signature: BytesLike, _bitmap: BigNumberish, _data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getTokenAddress: TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [_minFee: BigNumberish, _minBridgingAmount: BigNumberish, _minTokenBridgingAmount: BigNumberish, _minOperationFee: BigNumberish, _currencyTokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    minBridgingAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    minFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    minOperationFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    minTokenBridgingAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nativeTokenPredicate: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerToken: TypedContractMethod<
      [_lockUnlockSCAddress: AddressLike, _tokenId: BigNumberish, _name: string, _symbol: string, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setDependencies: TypedContractMethod<
      [_nativeTokenPredicateAddress: AddressLike, _tokenFactoryAddress: AddressLike, _validatorsAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMinAmounts: TypedContractMethod<
      [_minFee: BigNumberish, _minBridgingAmount: BigNumberish, _minTokenBridgingAmount: BigNumberish, _minOperationFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    tokenFactory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateValidatorsChainData: TypedContractMethod<
      [_signature: BytesLike, _bitmap: BigNumberish, _data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    

    
    validators: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    version: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [_destinationChainId: BigNumberish, _receivers: IGatewayStructs.ReceiverWithdrawStruct[], _fee: BigNumberish, _operationFee: BigNumberish, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'UPGRADE_INTERFACE_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'currencyTokenId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [_signature: BytesLike, _bitmap: BigNumberish, _data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTokenAddress'): TypedContractMethod<
      [_tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_minFee: BigNumberish, _minBridgingAmount: BigNumberish, _minTokenBridgingAmount: BigNumberish, _minOperationFee: BigNumberish, _currencyTokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'minBridgingAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'minFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'minOperationFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'minTokenBridgingAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nativeTokenPredicate'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerToken'): TypedContractMethod<
      [_lockUnlockSCAddress: AddressLike, _tokenId: BigNumberish, _name: string, _symbol: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDependencies'): TypedContractMethod<
      [_nativeTokenPredicateAddress: AddressLike, _tokenFactoryAddress: AddressLike, _validatorsAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinAmounts'): TypedContractMethod<
      [_minFee: BigNumberish, _minBridgingAmount: BigNumberish, _minTokenBridgingAmount: BigNumberish, _minOperationFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tokenFactory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateValidatorsChainData'): TypedContractMethod<
      [_signature: BytesLike, _bitmap: BigNumberish, _data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'validators'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'version'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [_destinationChainId: BigNumberish, _receivers: IGatewayStructs.ReceiverWithdrawStruct[], _fee: BigNumberish, _operationFee: BigNumberish, ],
      [void],
      'payable'
    >;

    getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'DepositedToken'): TypedContractEvent<DepositedTokenEvent.InputTuple, DepositedTokenEvent.OutputTuple, DepositedTokenEvent.OutputObject>;
getEvent(key: 'FundsDeposited'): TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'MinAmountsUpdated'): TypedContractEvent<MinAmountsUpdatedEvent.InputTuple, MinAmountsUpdatedEvent.OutputTuple, MinAmountsUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TTLExpired'): TypedContractEvent<TTLExpiredEvent.InputTuple, TTLExpiredEvent.OutputTuple, TTLExpiredEvent.OutputObject>;
getEvent(key: 'TokenRegistered'): TypedContractEvent<TokenRegisteredEvent.InputTuple, TokenRegisteredEvent.OutputTuple, TokenRegisteredEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
getEvent(key: 'ValidatorSetUpdatedGW'): TypedContractEvent<ValidatorSetUpdatedGWEvent.InputTuple, ValidatorSetUpdatedGWEvent.OutputTuple, ValidatorSetUpdatedGWEvent.OutputObject>;
getEvent(key: 'ValidatorsSetUpdated'): TypedContractEvent<ValidatorsSetUpdatedEvent.InputTuple, ValidatorsSetUpdatedEvent.OutputTuple, ValidatorsSetUpdatedEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
getEvent(key: 'WithdrawToken'): TypedContractEvent<WithdrawTokenEvent.InputTuple, WithdrawTokenEvent.OutputTuple, WithdrawTokenEvent.OutputObject>;

    filters: {
      
      'Deposit(bytes)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'DepositedToken(bytes)': TypedContractEvent<DepositedTokenEvent.InputTuple, DepositedTokenEvent.OutputTuple, DepositedTokenEvent.OutputObject>;
      DepositedToken: TypedContractEvent<DepositedTokenEvent.InputTuple, DepositedTokenEvent.OutputTuple, DepositedTokenEvent.OutputObject>;
    

      'FundsDeposited(address,uint256)': TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
      FundsDeposited: TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'MinAmountsUpdated(uint256,uint256,uint256,uint256)': TypedContractEvent<MinAmountsUpdatedEvent.InputTuple, MinAmountsUpdatedEvent.OutputTuple, MinAmountsUpdatedEvent.OutputObject>;
      MinAmountsUpdated: TypedContractEvent<MinAmountsUpdatedEvent.InputTuple, MinAmountsUpdatedEvent.OutputTuple, MinAmountsUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TTLExpired(bytes)': TypedContractEvent<TTLExpiredEvent.InputTuple, TTLExpiredEvent.OutputTuple, TTLExpiredEvent.OutputObject>;
      TTLExpired: TypedContractEvent<TTLExpiredEvent.InputTuple, TTLExpiredEvent.OutputTuple, TTLExpiredEvent.OutputObject>;
    

      'TokenRegistered(string,string,uint16,address,bool)': TypedContractEvent<TokenRegisteredEvent.InputTuple, TokenRegisteredEvent.OutputTuple, TokenRegisteredEvent.OutputObject>;
      TokenRegistered: TypedContractEvent<TokenRegisteredEvent.InputTuple, TokenRegisteredEvent.OutputTuple, TokenRegisteredEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    

      'ValidatorSetUpdatedGW(bytes)': TypedContractEvent<ValidatorSetUpdatedGWEvent.InputTuple, ValidatorSetUpdatedGWEvent.OutputTuple, ValidatorSetUpdatedGWEvent.OutputObject>;
      ValidatorSetUpdatedGW: TypedContractEvent<ValidatorSetUpdatedGWEvent.InputTuple, ValidatorSetUpdatedGWEvent.OutputTuple, ValidatorSetUpdatedGWEvent.OutputObject>;
    

      'ValidatorsSetUpdated(bytes)': TypedContractEvent<ValidatorsSetUpdatedEvent.InputTuple, ValidatorsSetUpdatedEvent.OutputTuple, ValidatorsSetUpdatedEvent.OutputObject>;
      ValidatorsSetUpdated: TypedContractEvent<ValidatorsSetUpdatedEvent.InputTuple, ValidatorsSetUpdatedEvent.OutputTuple, ValidatorsSetUpdatedEvent.OutputObject>;
    

      'Withdraw(uint8,address,tuple[],uint256,uint256,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    

      'WithdrawToken(address,string,uint256)': TypedContractEvent<WithdrawTokenEvent.InputTuple, WithdrawTokenEvent.OutputTuple, WithdrawTokenEvent.OutputObject>;
      WithdrawToken: TypedContractEvent<WithdrawTokenEvent.InputTuple, WithdrawTokenEvent.OutputTuple, WithdrawTokenEvent.OutputObject>;
    
    };
  }