/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockPrecompileFalse } from './MockPrecompileFalse.js';
export type { MockPrecompileTrue } from './MockPrecompileTrue.js';