/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IGatewayStructs {
      
    export type ReceiverWithdrawStruct = {receiver: string, amount: BigNumberish}

    export type ReceiverWithdrawStructOutput = [receiver: string, amount: bigint] & {receiver: string, amount: bigint }
  
    }

  export interface INativeTokenPredicateInterface extends Interface {
    getFunction(nameOrSignature: "deposit" | "resetBatchId"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposit" | "FundsDeposited" | "MinAmountsUpdated" | "TTLExpired" | "ValidatorSetUpdatedGW" | "ValidatorsSetUpdated" | "Withdraw"): EventFragment;

    encodeFunctionData(functionFragment: 'deposit', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'resetBatchId', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resetBatchId', data: BytesLike): Result;
  }

  
    export namespace DepositEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsDepositedEvent {
      export type InputTuple = [sender: AddressLike, value: BigNumberish];
      export type OutputTuple = [sender: string, value: bigint];
      export interface OutputObject {sender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinAmountsUpdatedEvent {
      export type InputTuple = [minFee: BigNumberish, minAmount: BigNumberish];
      export type OutputTuple = [minFee: bigint, minAmount: bigint];
      export interface OutputObject {minFee: bigint, minAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TTLExpiredEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidatorSetUpdatedGWEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidatorsSetUpdatedEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [destinationChainId: BigNumberish, sender: AddressLike, receivers: IGatewayStructs.ReceiverWithdrawStruct[], feeAmount: BigNumberish, value: BigNumberish];
      export type OutputTuple = [destinationChainId: bigint, sender: string, receivers: IGatewayStructs.ReceiverWithdrawStructOutput[], feeAmount: bigint, value: bigint];
      export interface OutputObject {destinationChainId: bigint, sender: string, receivers: IGatewayStructs.ReceiverWithdrawStructOutput[], feeAmount: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface INativeTokenPredicate extends BaseContract {
    
    connect(runner?: ContractRunner | null): INativeTokenPredicate;
    waitForDeployment(): Promise<this>;

    interface: INativeTokenPredicateInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    deposit: TypedContractMethod<
      [data: BytesLike, relayer: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    resetBatchId: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [data: BytesLike, relayer: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resetBatchId'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'FundsDeposited'): TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
getEvent(key: 'MinAmountsUpdated'): TypedContractEvent<MinAmountsUpdatedEvent.InputTuple, MinAmountsUpdatedEvent.OutputTuple, MinAmountsUpdatedEvent.OutputObject>;
getEvent(key: 'TTLExpired'): TypedContractEvent<TTLExpiredEvent.InputTuple, TTLExpiredEvent.OutputTuple, TTLExpiredEvent.OutputObject>;
getEvent(key: 'ValidatorSetUpdatedGW'): TypedContractEvent<ValidatorSetUpdatedGWEvent.InputTuple, ValidatorSetUpdatedGWEvent.OutputTuple, ValidatorSetUpdatedGWEvent.OutputObject>;
getEvent(key: 'ValidatorsSetUpdated'): TypedContractEvent<ValidatorsSetUpdatedEvent.InputTuple, ValidatorsSetUpdatedEvent.OutputTuple, ValidatorsSetUpdatedEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;

    filters: {
      
      'Deposit(bytes)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'FundsDeposited(address,uint256)': TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
      FundsDeposited: TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
    

      'MinAmountsUpdated(uint256,uint256)': TypedContractEvent<MinAmountsUpdatedEvent.InputTuple, MinAmountsUpdatedEvent.OutputTuple, MinAmountsUpdatedEvent.OutputObject>;
      MinAmountsUpdated: TypedContractEvent<MinAmountsUpdatedEvent.InputTuple, MinAmountsUpdatedEvent.OutputTuple, MinAmountsUpdatedEvent.OutputObject>;
    

      'TTLExpired(bytes)': TypedContractEvent<TTLExpiredEvent.InputTuple, TTLExpiredEvent.OutputTuple, TTLExpiredEvent.OutputObject>;
      TTLExpired: TypedContractEvent<TTLExpiredEvent.InputTuple, TTLExpiredEvent.OutputTuple, TTLExpiredEvent.OutputObject>;
    

      'ValidatorSetUpdatedGW(bytes)': TypedContractEvent<ValidatorSetUpdatedGWEvent.InputTuple, ValidatorSetUpdatedGWEvent.OutputTuple, ValidatorSetUpdatedGWEvent.OutputObject>;
      ValidatorSetUpdatedGW: TypedContractEvent<ValidatorSetUpdatedGWEvent.InputTuple, ValidatorSetUpdatedGWEvent.OutputTuple, ValidatorSetUpdatedGWEvent.OutputObject>;
    

      'ValidatorsSetUpdated(bytes)': TypedContractEvent<ValidatorsSetUpdatedEvent.InputTuple, ValidatorsSetUpdatedEvent.OutputTuple, ValidatorsSetUpdatedEvent.OutputObject>;
      ValidatorsSetUpdated: TypedContractEvent<ValidatorsSetUpdatedEvent.InputTuple, ValidatorsSetUpdatedEvent.OutputTuple, ValidatorsSetUpdatedEvent.OutputObject>;
    

      'Withdraw(uint8,address,tuple[],uint256,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    
    };
  }