/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IGatewayStructs {
      
    export type ReceiverWithdrawStruct = {receiver: string, amount: BigNumberish, tokenId: BigNumberish}

    export type ReceiverWithdrawStructOutput = [receiver: string, amount: bigint, tokenId: bigint] & {receiver: string, amount: bigint, tokenId: bigint }
  

    export type TokenInfoStruct = {addr: AddressLike, isLockUnlock: boolean}

    export type TokenInfoStructOutput = [addr: string, isLockUnlock: boolean] & {addr: string, isLockUnlock: boolean }
  
    }

  export interface INativeTokenPredicateInterface extends Interface {
    getFunction(nameOrSignature: "deposit" | "getNativeTokenWalletAddress" | "getTokenInfo" | "resetBatchId" | "setTokenInfo" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposit" | "DepositedToken" | "FundsDeposited" | "MinAmountsUpdated" | "TTLExpired" | "TokenRegistered" | "ValidatorSetUpdatedGW" | "ValidatorsSetUpdated" | "Withdraw" | "WithdrawToken"): EventFragment;

    encodeFunctionData(functionFragment: 'deposit', values: [BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getNativeTokenWalletAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTokenInfo', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resetBatchId', values?: undefined): string;
encodeFunctionData(functionFragment: 'setTokenInfo', values: [BigNumberish, AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [AddressLike, IGatewayStructs.ReceiverWithdrawStruct]): string;

    decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNativeTokenWalletAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resetBatchId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTokenInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace DepositEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositedTokenEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsDepositedEvent {
      export type InputTuple = [sender: AddressLike, value: BigNumberish];
      export type OutputTuple = [sender: string, value: bigint];
      export interface OutputObject {sender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinAmountsUpdatedEvent {
      export type InputTuple = [minFee: BigNumberish, minAmount: BigNumberish, minTokenAmount: BigNumberish, minOperationFee: BigNumberish];
      export type OutputTuple = [minFee: bigint, minAmount: bigint, minTokenAmount: bigint, minOperationFee: bigint];
      export interface OutputObject {minFee: bigint, minAmount: bigint, minTokenAmount: bigint, minOperationFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TTLExpiredEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenRegisteredEvent {
      export type InputTuple = [name: string, symbol: string, tokenId: BigNumberish, contractAddress: AddressLike, isLockUnlockToken: boolean];
      export type OutputTuple = [name: string, symbol: string, tokenId: bigint, contractAddress: string, isLockUnlockToken: boolean];
      export interface OutputObject {name: string, symbol: string, tokenId: bigint, contractAddress: string, isLockUnlockToken: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidatorSetUpdatedGWEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidatorsSetUpdatedEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [destinationChainId: BigNumberish, sender: AddressLike, receivers: IGatewayStructs.ReceiverWithdrawStruct[], fee: BigNumberish, operationFee: BigNumberish, value: BigNumberish];
      export type OutputTuple = [destinationChainId: bigint, sender: string, receivers: IGatewayStructs.ReceiverWithdrawStructOutput[], fee: bigint, operationFee: bigint, value: bigint];
      export interface OutputObject {destinationChainId: bigint, sender: string, receivers: IGatewayStructs.ReceiverWithdrawStructOutput[], fee: bigint, operationFee: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawTokenEvent {
      export type InputTuple = [sender: AddressLike, receiver: string, amount: BigNumberish];
      export type OutputTuple = [sender: string, receiver: string, amount: bigint];
      export interface OutputObject {sender: string, receiver: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface INativeTokenPredicate extends BaseContract {
    
    connect(runner?: ContractRunner | null): INativeTokenPredicate;
    waitForDeployment(): Promise<this>;

    interface: INativeTokenPredicateInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    deposit: TypedContractMethod<
      [data: BytesLike, relayer: AddressLike, currencyTokenId: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    getNativeTokenWalletAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getTokenInfo: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [IGatewayStructs.TokenInfoStructOutput],
      'view'
    >
    

    
    resetBatchId: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setTokenInfo: TypedContractMethod<
      [tokenId: BigNumberish, tokenAddress: AddressLike, isLockUnlock: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [sender: AddressLike, _receiver: IGatewayStructs.ReceiverWithdrawStruct, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [data: BytesLike, relayer: AddressLike, currencyTokenId: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getNativeTokenWalletAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenInfo'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [IGatewayStructs.TokenInfoStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'resetBatchId'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTokenInfo'): TypedContractMethod<
      [tokenId: BigNumberish, tokenAddress: AddressLike, isLockUnlock: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [sender: AddressLike, _receiver: IGatewayStructs.ReceiverWithdrawStruct, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'DepositedToken'): TypedContractEvent<DepositedTokenEvent.InputTuple, DepositedTokenEvent.OutputTuple, DepositedTokenEvent.OutputObject>;
getEvent(key: 'FundsDeposited'): TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
getEvent(key: 'MinAmountsUpdated'): TypedContractEvent<MinAmountsUpdatedEvent.InputTuple, MinAmountsUpdatedEvent.OutputTuple, MinAmountsUpdatedEvent.OutputObject>;
getEvent(key: 'TTLExpired'): TypedContractEvent<TTLExpiredEvent.InputTuple, TTLExpiredEvent.OutputTuple, TTLExpiredEvent.OutputObject>;
getEvent(key: 'TokenRegistered'): TypedContractEvent<TokenRegisteredEvent.InputTuple, TokenRegisteredEvent.OutputTuple, TokenRegisteredEvent.OutputObject>;
getEvent(key: 'ValidatorSetUpdatedGW'): TypedContractEvent<ValidatorSetUpdatedGWEvent.InputTuple, ValidatorSetUpdatedGWEvent.OutputTuple, ValidatorSetUpdatedGWEvent.OutputObject>;
getEvent(key: 'ValidatorsSetUpdated'): TypedContractEvent<ValidatorsSetUpdatedEvent.InputTuple, ValidatorsSetUpdatedEvent.OutputTuple, ValidatorsSetUpdatedEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
getEvent(key: 'WithdrawToken'): TypedContractEvent<WithdrawTokenEvent.InputTuple, WithdrawTokenEvent.OutputTuple, WithdrawTokenEvent.OutputObject>;

    filters: {
      
      'Deposit(bytes)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'DepositedToken(bytes)': TypedContractEvent<DepositedTokenEvent.InputTuple, DepositedTokenEvent.OutputTuple, DepositedTokenEvent.OutputObject>;
      DepositedToken: TypedContractEvent<DepositedTokenEvent.InputTuple, DepositedTokenEvent.OutputTuple, DepositedTokenEvent.OutputObject>;
    

      'FundsDeposited(address,uint256)': TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
      FundsDeposited: TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
    

      'MinAmountsUpdated(uint256,uint256,uint256,uint256)': TypedContractEvent<MinAmountsUpdatedEvent.InputTuple, MinAmountsUpdatedEvent.OutputTuple, MinAmountsUpdatedEvent.OutputObject>;
      MinAmountsUpdated: TypedContractEvent<MinAmountsUpdatedEvent.InputTuple, MinAmountsUpdatedEvent.OutputTuple, MinAmountsUpdatedEvent.OutputObject>;
    

      'TTLExpired(bytes)': TypedContractEvent<TTLExpiredEvent.InputTuple, TTLExpiredEvent.OutputTuple, TTLExpiredEvent.OutputObject>;
      TTLExpired: TypedContractEvent<TTLExpiredEvent.InputTuple, TTLExpiredEvent.OutputTuple, TTLExpiredEvent.OutputObject>;
    

      'TokenRegistered(string,string,uint16,address,bool)': TypedContractEvent<TokenRegisteredEvent.InputTuple, TokenRegisteredEvent.OutputTuple, TokenRegisteredEvent.OutputObject>;
      TokenRegistered: TypedContractEvent<TokenRegisteredEvent.InputTuple, TokenRegisteredEvent.OutputTuple, TokenRegisteredEvent.OutputObject>;
    

      'ValidatorSetUpdatedGW(bytes)': TypedContractEvent<ValidatorSetUpdatedGWEvent.InputTuple, ValidatorSetUpdatedGWEvent.OutputTuple, ValidatorSetUpdatedGWEvent.OutputObject>;
      ValidatorSetUpdatedGW: TypedContractEvent<ValidatorSetUpdatedGWEvent.InputTuple, ValidatorSetUpdatedGWEvent.OutputTuple, ValidatorSetUpdatedGWEvent.OutputObject>;
    

      'ValidatorsSetUpdated(bytes)': TypedContractEvent<ValidatorsSetUpdatedEvent.InputTuple, ValidatorsSetUpdatedEvent.OutputTuple, ValidatorsSetUpdatedEvent.OutputObject>;
      ValidatorsSetUpdated: TypedContractEvent<ValidatorsSetUpdatedEvent.InputTuple, ValidatorsSetUpdatedEvent.OutputTuple, ValidatorsSetUpdatedEvent.OutputObject>;
    

      'Withdraw(uint8,address,tuple[],uint256,uint256,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    

      'WithdrawToken(address,string,uint256)': TypedContractEvent<WithdrawTokenEvent.InputTuple, WithdrawTokenEvent.OutputTuple, WithdrawTokenEvent.OutputObject>;
      WithdrawToken: TypedContractEvent<WithdrawTokenEvent.InputTuple, WithdrawTokenEvent.OutputTuple, WithdrawTokenEvent.OutputObject>;
    
    };
  }