/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGateway } from './IGateway.js';
export type { IGatewayStructs } from './IGatewayStructs.js';
export type { INativeTokenPredicate } from './INativeTokenPredicate.js';
export type { INativeTokenWallet } from './INativeTokenWallet.js';
export type { IValidators } from './IValidators.js';