/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IGatewayStructs {
      
    export type ReceiverWithdrawStruct = {receiver: string, amount: BigNumberish}

    export type ReceiverWithdrawStructOutput = [receiver: string, amount: bigint] & {receiver: string, amount: bigint }
  

    export type ValidatorChainDataStruct = {key: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]}

    export type ValidatorChainDataStructOutput = [key: [bigint, bigint, bigint, bigint]] & {key: [bigint, bigint, bigint, bigint] }
  
    }

  export interface IValidatorsInterface extends Interface {
    getFunction(nameOrSignature: "getValidatorsChainData" | "isBlsSignatureValid" | "setValidatorsChainData" | "updateValidatorsChainData"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposit" | "FundsDeposited" | "MinAmountsUpdated" | "TTLExpired" | "ValidatorSetUpdatedGW" | "ValidatorsSetUpdated" | "Withdraw"): EventFragment;

    encodeFunctionData(functionFragment: 'getValidatorsChainData', values?: undefined): string;
encodeFunctionData(functionFragment: 'isBlsSignatureValid', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setValidatorsChainData', values: [IGatewayStructs.ValidatorChainDataStruct[]]): string;
encodeFunctionData(functionFragment: 'updateValidatorsChainData', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getValidatorsChainData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isBlsSignatureValid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setValidatorsChainData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateValidatorsChainData', data: BytesLike): Result;
  }

  
    export namespace DepositEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsDepositedEvent {
      export type InputTuple = [sender: AddressLike, value: BigNumberish];
      export type OutputTuple = [sender: string, value: bigint];
      export interface OutputObject {sender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinAmountsUpdatedEvent {
      export type InputTuple = [minFee: BigNumberish, minAmount: BigNumberish];
      export type OutputTuple = [minFee: bigint, minAmount: bigint];
      export interface OutputObject {minFee: bigint, minAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TTLExpiredEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidatorSetUpdatedGWEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ValidatorsSetUpdatedEvent {
      export type InputTuple = [data: BytesLike];
      export type OutputTuple = [data: string];
      export interface OutputObject {data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawEvent {
      export type InputTuple = [destinationChainId: BigNumberish, sender: AddressLike, receivers: IGatewayStructs.ReceiverWithdrawStruct[], feeAmount: BigNumberish, value: BigNumberish];
      export type OutputTuple = [destinationChainId: bigint, sender: string, receivers: IGatewayStructs.ReceiverWithdrawStructOutput[], feeAmount: bigint, value: bigint];
      export interface OutputObject {destinationChainId: bigint, sender: string, receivers: IGatewayStructs.ReceiverWithdrawStructOutput[], feeAmount: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IValidators extends BaseContract {
    
    connect(runner?: ContractRunner | null): IValidators;
    waitForDeployment(): Promise<this>;

    interface: IValidatorsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getValidatorsChainData: TypedContractMethod<
      [],
      [IGatewayStructs.ValidatorChainDataStructOutput[]],
      'view'
    >
    

    
    isBlsSignatureValid: TypedContractMethod<
      [_hash: BytesLike, _signature: BytesLike, _bitmap: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    setValidatorsChainData: TypedContractMethod<
      [_validatorsChainData: IGatewayStructs.ValidatorChainDataStruct[], ],
      [void],
      'nonpayable'
    >
    

    
    updateValidatorsChainData: TypedContractMethod<
      [_data: BytesLike, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getValidatorsChainData'): TypedContractMethod<
      [],
      [IGatewayStructs.ValidatorChainDataStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'isBlsSignatureValid'): TypedContractMethod<
      [_hash: BytesLike, _signature: BytesLike, _bitmap: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setValidatorsChainData'): TypedContractMethod<
      [_validatorsChainData: IGatewayStructs.ValidatorChainDataStruct[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateValidatorsChainData'): TypedContractMethod<
      [_data: BytesLike, ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'FundsDeposited'): TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
getEvent(key: 'MinAmountsUpdated'): TypedContractEvent<MinAmountsUpdatedEvent.InputTuple, MinAmountsUpdatedEvent.OutputTuple, MinAmountsUpdatedEvent.OutputObject>;
getEvent(key: 'TTLExpired'): TypedContractEvent<TTLExpiredEvent.InputTuple, TTLExpiredEvent.OutputTuple, TTLExpiredEvent.OutputObject>;
getEvent(key: 'ValidatorSetUpdatedGW'): TypedContractEvent<ValidatorSetUpdatedGWEvent.InputTuple, ValidatorSetUpdatedGWEvent.OutputTuple, ValidatorSetUpdatedGWEvent.OutputObject>;
getEvent(key: 'ValidatorsSetUpdated'): TypedContractEvent<ValidatorsSetUpdatedEvent.InputTuple, ValidatorsSetUpdatedEvent.OutputTuple, ValidatorsSetUpdatedEvent.OutputObject>;
getEvent(key: 'Withdraw'): TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;

    filters: {
      
      'Deposit(bytes)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'FundsDeposited(address,uint256)': TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
      FundsDeposited: TypedContractEvent<FundsDepositedEvent.InputTuple, FundsDepositedEvent.OutputTuple, FundsDepositedEvent.OutputObject>;
    

      'MinAmountsUpdated(uint256,uint256)': TypedContractEvent<MinAmountsUpdatedEvent.InputTuple, MinAmountsUpdatedEvent.OutputTuple, MinAmountsUpdatedEvent.OutputObject>;
      MinAmountsUpdated: TypedContractEvent<MinAmountsUpdatedEvent.InputTuple, MinAmountsUpdatedEvent.OutputTuple, MinAmountsUpdatedEvent.OutputObject>;
    

      'TTLExpired(bytes)': TypedContractEvent<TTLExpiredEvent.InputTuple, TTLExpiredEvent.OutputTuple, TTLExpiredEvent.OutputObject>;
      TTLExpired: TypedContractEvent<TTLExpiredEvent.InputTuple, TTLExpiredEvent.OutputTuple, TTLExpiredEvent.OutputObject>;
    

      'ValidatorSetUpdatedGW(bytes)': TypedContractEvent<ValidatorSetUpdatedGWEvent.InputTuple, ValidatorSetUpdatedGWEvent.OutputTuple, ValidatorSetUpdatedGWEvent.OutputObject>;
      ValidatorSetUpdatedGW: TypedContractEvent<ValidatorSetUpdatedGWEvent.InputTuple, ValidatorSetUpdatedGWEvent.OutputTuple, ValidatorSetUpdatedGWEvent.OutputObject>;
    

      'ValidatorsSetUpdated(bytes)': TypedContractEvent<ValidatorsSetUpdatedEvent.InputTuple, ValidatorsSetUpdatedEvent.OutputTuple, ValidatorsSetUpdatedEvent.OutputObject>;
      ValidatorsSetUpdated: TypedContractEvent<ValidatorsSetUpdatedEvent.InputTuple, ValidatorsSetUpdatedEvent.OutputTuple, ValidatorsSetUpdatedEvent.OutputObject>;
    

      'Withdraw(uint8,address,tuple[],uint256,uint256)': TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
      Withdraw: TypedContractEvent<WithdrawEvent.InputTuple, WithdrawEvent.OutputTuple, WithdrawEvent.OutputObject>;
    
    };
  }