/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockPrecompileFalse, MockPrecompileFalseInterface } from "../../mocks/MockPrecompileFalse.js";

  const _abi = [
  {
    "stateMutability": "nonpayable",
    "type": "fallback"
  }
] as const;

  const _bytecode = "0x6080806040523461001657610101908161001c8239f35b600080fdfe60803460c657600060209181602082015260208152604081019167ffffffffffffffff918084108385111760b257836040526060810194828652604060808301528151908160a0840152835b828110609f57505090601f609f82848660c06040978401015283199384910116810103606081018852011601019183831090831117608b57506040525190f35b634e487b7160e01b81526041600452602490fd5b808291850160c08382015191015201604b565b634e487b7160e01b82526041600452602482fd5b600080fdfea2646970667358221220dde2d2fef5ab27c7b36d5811632049bb3f98268f11ee634c38d6b36d9769e77464736f6c63430008180033";

  
      type MockPrecompileFalseConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockPrecompileFalseConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockPrecompileFalse__factory extends ContractFactory {
    
      constructor(...args: MockPrecompileFalseConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockPrecompileFalse & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockPrecompileFalse__factory {
      return super.connect(runner) as MockPrecompileFalse__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockPrecompileFalseInterface {
      return new Interface(_abi) as MockPrecompileFalseInterface;
    }
    
    override attach(address: string | Addressable): MockPrecompileFalse {
      return super.attach(address) as MockPrecompileFalse;
    }
  static connect(address: string, runner?: ContractRunner | null): MockPrecompileFalse {
      return new Contract(address, _abi, runner) as unknown as MockPrecompileFalse;
    }
  }

  
  