/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockPrecompileTrue, MockPrecompileTrueInterface } from "../../Mocks/MockPrecompileTrue.js";

  const _abi = [
  {
    "stateMutability": "nonpayable",
    "type": "fallback"
  }
] as const;

  const _bytecode = "0x608080604052346100155760f0908161001b8239f35b600080fdfe60803460b5576020906001602082015260208152604081019067ffffffffffffffff9080831082841117608c5782604052606081019360018552604060808301528151908160a084015260005b82811060a257505090601f609f8284600060c06040978401015283199384910116810103606081018752011601019082821090821117608c576040525190f35b634e487b7160e01b600052604160045260246000fd5b808291850160c08382015191015201604c565b600080fdfea26469706673582212202c683df88a29feff477bc14516e61307ec954d7c0fd682062050dbd74b9824dd64736f6c63430008180033";

  
      type MockPrecompileTrueConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockPrecompileTrueConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockPrecompileTrue__factory extends ContractFactory {
    
      constructor(...args: MockPrecompileTrueConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockPrecompileTrue & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockPrecompileTrue__factory {
      return super.connect(runner) as MockPrecompileTrue__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockPrecompileTrueInterface {
      return new Interface(_abi) as MockPrecompileTrueInterface;
    }
    
    override attach(address: string | Addressable): MockPrecompileTrue {
      return super.attach(address) as MockPrecompileTrue;
    }
  static connect(address: string, runner?: ContractRunner | null): MockPrecompileTrue {
      return new Contract(address, _abi, runner) as unknown as MockPrecompileTrue;
    }
  }

  
  